services:
  nexus:
    image: sonatype/nexus3:3.89.1
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms1500m -Xmx1500m -XX:MaxDirectMemorySize=1500m
    volumes:
      - nexus-data:/nexus-data

  proxy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "443:443"
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - ./infra/caddy-data:/data
    depends_on:
      - nexus

volumes:
  nexus-data:
